# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: svn2git3 3.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "svn2git3".freeze
  s.version = "3.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["James Coglan".freeze, "Kevin Menard".freeze, "Abao".freeze]
  s.date = "2022-06-07"
  s.email = "ibaoger@hotmail.com".freeze
  s.executables = ["svn2git".freeze]
  s.extra_rdoc_files = [
    "ChangeLog.markdown",
    "README.markdown"
  ]
  s.files = [
    "ChangeLog.markdown",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION.yml",
    "bin/svn2git",
    "lib/svn2git.rb",
    "lib/svn2git/migration.rb",
    "svn2git3.gemspec",
    "test/commands_test.rb",
    "test/escape_quotes_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "https://github.com/ibaoger/svn2git3".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "A tool for migrating svn projects to git".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<minitest>.freeze, [">= 0"])
  else
    s.add_dependency(%q<minitest>.freeze, [">= 0"])
  end
end

